### ISSUE TITLE
Make the level up code modify all base stats (see comment)

### ISSUE THREAD

**Issue by phoenixanimations** [phoenixanimations/TheNuwasFile#36]
+ [ ] Combat Level
+ [ ] Melee Accuracy
+ [ ] Magic Accuracy
+ [ ] Archery Accuracy
+ [ ] Melee Evade
+ [ ] Magic Evade
+ [ ] Archery Evade

**Comment by RVNJ** [comment]
Will add these fixes tomorrow (uhh .. today?) morning

**Comment by RVNJ** [comment]
Okay, this is more complicated than I expected, based on how I use the Tier Array to formulate your Combat Level. We're going to need to collaborate on this one, at least for the start.

**Comment by phoenixanimations** [comment]
So I added a combat node. So now we can make a separate attribute (that has the highest spell speed) that just modifies the combat level. 

Are these the right numbers?
```
1, 1, 1, 1 = 0
100, 1, 1, 1 = 81
100, 100, 1, 1 = 91
40, 50, 60, 70 = 60
```

**Comment by RVNJ** [comment]
All relevant stats accounted for.

1, 1, 1, 1 = 1
100, 1, 1, 1 = 80
100, 100, 1, 1 = 90
40, 50, 60, 70 = 59

I know why you got the numbers you did; it's something I'll have to explain tomorrow and it's half of the headache for tonight (the other half was unexpected stack overflow errors coming from stats that were reset because they defaulted back to base stats -- it's complicated). Anyhow, I'm content with this for now. I expect I'll go through and clean it up at some point in the future just because I hate using +1/-1 to resolve stat errors.
