### ISSUE TITLE
Add new Character Sheet Stats

### ISSUE THREAD

**Issue by RVNJ** [phoenixanimations/TheNuwasFile#71]
- [ ] Add Air Damage Multiplier
- [ ] Add Water Damage Multiplier
- [ ] Add Earth Damage Multiplier
- [ ] Add Fire Damage Multiplier
- [ ] Add Energy (Spell-Type) Damage Multiplier
- [ ] Add Light Damage Multiplier
- [ ] Add Dark Damage Multiplier
- [ ] Add Holy Damage Multiplier
- [ ] Add Unholy Damage Multiplier
- [ ] Add Length (Dimensions)
- [ ] Add Width (Dimensions)
- [ ] Add Height (Dimensions)

... possibly more to come

**Comment by phoenixanimations** [comment]
Possibly also add?
Air Resistance, etc

**Comment by RVNJ** [comment]
if we add acc/evd/res multipliers the character sheet is going to become very cumbersome to navigate - that's why I had an issue with these at first, we may even just have to forgo the idea just because it's too much - I'm going to hold off on those for now

**Comment by phoenixanimations** [comment]
Yea, I'm thinking in the rewrite I design the characters sheet to be easier to navigate. And add something than can hide/collapse sections.

**Comment by RVNJ** [comment]
I think I would prefer to handle this differently. Here's what I'm thinking:
Enemies with a specific 'type' of weakness will have a Passive attributed to that type, which gives them the 'Weak to X' 'Defect'/Debuff

Therefore, 'Tree' having a 'Fire' weakness will give the Tree target the Passive 'Weak to Fire'/'Fire Weakness', which spawns a similarly named 'Defect'/Debuff with the attached Variables:
- Level (1 is as it is spawned, 0 is to despawn)
- Damage Multiplier
- Accuracy Multiplier
- Evade Multiplier
- Critical Damage Multiplier
- Critical Chance Addition (we never multiply Crit Chance, it's ... complicated)

**Comment by phoenixanimations** [comment]
So how will the tree know the damage being dealt is fire? I assume by reading a tag on the weapon. This is my only problem with the method. 

Because it makes having the active: weapon does fire damage tricky to implement. I.e. all spells in the game. Does the spell add a tag to the weapon temporary?

If the passive reads what spell you have equipped consider, a melee weapon with an active: at 50% energy do fire damage. 

Something to note is this isn't just spells here, we also want blunt damage or sharp damage. Your implemention accounts for that. It can also account for the fire melee active we just gotta agree on how. 

Ps. If you want critical chance to be additive only (or do you mean just for fire? A bit confused on why that stat is there) keep in mind you can't have something that says halve critical chance.

**Comment by phoenixanimations** [comment]
Okay so what we agree on (phone call). 

Tree:
Fire Weakness  (state is "none")

Weapon 
Fire
Searches enemy and of Fire Weakness is there turn it on. 

Tree? Turns off? Passive? Unsure possible evaluate bonuses problem #37.

**Comment by RVNJ** [comment]
Defunct
